services:
  # Сервис MySQL
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      # Том для данных (оставляем, но удалим при полной пересборке)
      - db-data:/var/lib/mysql
      # Примонтировать скрипт инициализации
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql:ro
    networks:
      - todonet

  # Веб-приложение на Express
  app:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - todonet

  # Telegram-бот
  bot:
    build: .
    command: ["node", "bot.js"]
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - todonet

  # Nginx-прокси
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - todonet

volumes:
  db-data:

networks:
  todonet:
    driver: bridge



